// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iivzarjobpuerkdpngrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpdnphcmpvYnB1ZXJrZHBuZ3JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjcwNjUsImV4cCI6MjA2NTY0MzA2NX0.yaCsmLEy-yllTVZf1JvVH4hfjHLXu4wxykZn5s4yM40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);